name: Deploy PR previews

on:
  pull_request:
    branches:
      - main

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Generate type documentation
        run: yarn generate
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs/
