name: Js-sdsl test CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run unit test
        run: yarn test:unit
      - name: Coveralls report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
  browser-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run browser test
        run: yarn test:browser
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run performance test
        run: yarn test:performance
