name: Js-sdsl test CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run unit test
        run: yarn test:unit
      - name: Coveralls report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
  browser-chrome-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run chrome test
        run: yarn test:chrome
  browser-firefox-test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: '31.0'
      - name: Run firefox test
        run: FIREFOX_BIN=$(which firefox) yarn test:firefox
  browser-edge-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Setup edge
        uses: browser-actions/setup-edge@latest
      - name: Run edge test
        run: yarn test:edge
  browser-safari-test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run safari test
        run: yarn test:safari
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Use node.js lts/Gallium
        uses: actions/setup-node@v3
        with:
          node-version: lts/Gallium
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run performance test
        run: yarn test:performance
